# Generated by Django 5.1.7 on 2025-03-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_location_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='is_mutual',
        ),
    ]
