# Generated by Django 5.1.7 on 2025-03-08 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_match_is_mutual'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainstreamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated'), ('WIDOWED', 'Widowed')], max_length=10)),
                ('looking_for', models.CharField(blank=True, choices=[('DATING', 'Dating'), ('RELATIONSHIP', 'Relationship'), ('FRIENDSHIP', 'Friendship'), ('MARRIAGE', 'Marriage')], max_length=12)),
                ('education_level', models.CharField(blank=True, choices=[('HIGH_SCHOOL', 'High School'), ('COLLEGE', 'College'), ('BACHELORS', "Bachelor's Degree"), ('MASTERS', "Master's Degree"), ('DOCTORATE', 'Doctorate')], max_length=15)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('interested_in_gender', models.CharField(blank=True, max_length=10)),
                ('has_children', models.BooleanField(blank=True, null=True)),
                ('wants_children', models.BooleanField(blank=True, null=True)),
                ('smoker', models.BooleanField(blank=True, null=True)),
                ('drinker', models.BooleanField(blank=True, null=True)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='mainstream/photos/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='mainstream/photos/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='mainstream/photos/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='mainstream/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mainstream_profile', to='core.profile')),
            ],
        ),
    ]
