# Generated by Django 5.1.7 on 2025-05-25 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the ethnicity (e.g., Han Chinese, Yoruba, Andalusian)', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ethnicity',
                'verbose_name_plural': 'Ethnicities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the language (e.g., English, Mandarin, Spanish)', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EthnicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_country', models.CharField(blank=True, help_text='Country you consider home or grew up in.', max_length=100, verbose_name='Home Country')),
                ('cultural_values_description', models.TextField(blank=True, help_text='Briefly describe your cultural values or upbringing.', verbose_name='Cultural Values Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('ethnicities', models.ManyToManyField(blank=True, help_text='Select one or more ethnicities that you identify with.', to='ethnic.ethnicity', verbose_name='Ethnicities')),
                ('partner_ethnicity_preference', models.ManyToManyField(blank=True, help_text='Ethnicities you are interested in for a partner.', related_name='preferred_by_ethnic_profiles', to='ethnic.ethnicity', verbose_name='Partner Ethnicity Preference')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ethnic_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('languages_spoken', models.ManyToManyField(blank=True, help_text='Languages you speak fluently.', to='ethnic.language', verbose_name='Languages Spoken')),
                ('partner_language_preference', models.ManyToManyField(blank=True, help_text="Languages you'd prefer your partner to speak.", related_name='preferred_by_ethnic_profiles_lang', to='ethnic.language', verbose_name='Partner Language Preference')),
            ],
            options={
                'verbose_name': 'Ethnic Profile',
                'verbose_name_plural': 'Ethnic Profiles',
            },
        ),
    ]
