# Generated by Django ... on ...
# ethnic/migrations/0002_populate_initial_ethnic_data.py

from django.db import migrations

def populate_ethnicities(apps, schema_editor):
    Ethnicity = apps.get_model('ethnic', 'Ethnicity')
    ethnicities_data = [
        'African', 'African American', 'Asian', 'Caribbean', 'East Asian', 
        'European', 'Hispanic/Latino', 'Middle Eastern', 'Native American', 
        'Pacific Islander', 'South Asian', 'Southeast Asian', 'Mixed Heritage', 'Other'
    ]
    for name in ethnicities_data:
        Ethnicity.objects.get_or_create(name=name)

def populate_languages(apps, schema_editor):
    Language = apps.get_model('ethnic', 'Language')
    languages_data = [
        'English', 'Spanish', 'French', 'German', 'Mandarin', 'Cantonese', 
        'Hindi', 'Urdu', 'Arabic', 'Portuguese', 'Bengali', 'Russian', 
        'Japanese', 'Korean', 'Italian', 'Dutch', 'Swedish', 'Norwegian', 
        'Danish', 'Finnish', 'Polish', 'Turkish', 'Vietnamese', 'Thai', 
        'Tagalog', 'Swahili', 'Other'
    ]
    for name in languages_data:
        Language.objects.get_or_create(name=name)

def remove_ethnicities(apps, schema_editor):
    Ethnicity = apps.get_model('ethnic', 'Ethnicity')
    # This is a simple revert; for production, consider if data should be truly deleted or just deactivated
    Ethnicity.objects.all().delete() 

def remove_languages(apps, schema_editor):
    Language = apps.get_model('ethnic', 'Language')
    Language.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('ethnic', '0001_initial'), # Depends on the previous schema migration
    ]

    operations = [
        migrations.RunPython(populate_ethnicities, reverse_code=remove_ethnicities),
        migrations.RunPython(populate_languages, reverse_code=remove_languages),
    ]
