# Generated by Django 5.1.7 on 2025-03-07 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lgbtq_events/')),
                ('is_private', models.BooleanField(default=False)),
                ('is_pride', models.BooleanField(default=False)),
                ('is_support_group', models.BooleanField(default=False)),
                ('is_social', models.BooleanField(default=False)),
                ('is_educational', models.BooleanField(default=False)),
                ('attendees', models.ManyToManyField(related_name='attending_lgbtq_events', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_lgbtq_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('ARTICLE', 'Article'), ('VIDEO', 'Video'), ('PODCAST', 'Podcast'), ('ORGANIZATION', 'Organization'), ('SUPPORT', 'Support Service'), ('LEGAL', 'Legal Resource'), ('HEALTH', 'Health Resource')], max_length=15)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lgbtq_resources/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_for_youth', models.BooleanField(default=False)),
                ('is_for_trans', models.BooleanField(default=False)),
                ('is_for_parents', models.BooleanField(default=False)),
                ('is_for_allies', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LGBTQProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_identity', models.CharField(blank=True, choices=[('CIS_MALE', 'Cisgender Male'), ('CIS_FEMALE', 'Cisgender Female'), ('TRANS_MALE', 'Transgender Male'), ('TRANS_FEMALE', 'Transgender Female'), ('NON_BINARY', 'Non-Binary'), ('GENDERFLUID', 'Genderfluid'), ('GENDERQUEER', 'Genderqueer'), ('AGENDER', 'Agender'), ('OTHER', 'Other')], max_length=15)),
                ('sexual_orientation', models.CharField(blank=True, choices=[('GAY', 'Gay'), ('LESBIAN', 'Lesbian'), ('BISEXUAL', 'Bisexual'), ('PANSEXUAL', 'Pansexual'), ('ASEXUAL', 'Asexual'), ('DEMISEXUAL', 'Demisexual'), ('QUEER', 'Queer'), ('QUESTIONING', 'Questioning'), ('OTHER', 'Other')], max_length=15)),
                ('pronouns', models.CharField(blank=True, choices=[('HE_HIM', 'He/Him'), ('SHE_HER', 'She/Her'), ('THEY_THEM', 'They/Them'), ('ZE_HIR', 'Ze/Hir'), ('XE_XEM', 'Xe/Xem'), ('CUSTOM', 'Custom')], max_length=10)),
                ('custom_pronouns', models.CharField(blank=True, max_length=50)),
                ('is_out', models.BooleanField(default=True)),
                ('coming_out_story', models.TextField(blank=True)),
                ('is_community_member', models.BooleanField(default=False)),
                ('community_roles', models.TextField(blank=True)),
                ('open_to_dating_trans', models.BooleanField(default=True)),
                ('open_to_dating_non_binary', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lgbtq_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
