# Generated by Django 5.1.7 on 2025-03-07 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='income_verification/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LuxuryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_exclusive', models.BooleanField(default=True)),
                ('max_attendees', models.IntegerField(default=50)),
                ('attendees', models.ManyToManyField(related_name='attending_events', through='sugar.EventAttendee', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sugar.luxuryevent'),
        ),
        migrations.CreateModel(
            name='SugarProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sugar_daddy', models.BooleanField(default=False)),
                ('is_sugar_mommy', models.BooleanField(default=False)),
                ('is_sugar_baby', models.BooleanField(default=False)),
                ('income_range', models.CharField(blank=True, choices=[('1', 'Under $50,000'), ('2', '$50,000 - $100,000'), ('3', '$100,000 - $250,000'), ('4', '$250,000 - $500,000'), ('5', '$500,000 - $1,000,000'), ('6', 'Over $1,000,000'), ('7', 'Prefer not to say')], max_length=1)),
                ('net_worth_range', models.CharField(blank=True, choices=[('1', 'Under $50,000'), ('2', '$50,000 - $100,000'), ('3', '$100,000 - $250,000'), ('4', '$250,000 - $500,000'), ('5', '$500,000 - $1,000,000'), ('6', 'Over $1,000,000'), ('7', 'Prefer not to say')], max_length=1)),
                ('is_income_verified', models.BooleanField(default=False)),
                ('lifestyle', models.CharField(blank=True, choices=[('MODEST', 'Modest'), ('COMFORTABLE', 'Comfortable'), ('WEALTHY', 'Wealthy'), ('LUXURIOUS', 'Luxurious')], max_length=15)),
                ('relationship_type', models.CharField(blank=True, choices=[('PLATONIC', 'Platonic'), ('ROMANTIC', 'Romantic'), ('MENTORSHIP', 'Mentorship'), ('TRAVEL', 'Travel Partner'), ('FLEXIBLE', 'Flexible')], max_length=15)),
                ('allowance_expectations', models.TextField(blank=True)),
                ('travel_preferences', models.TextField(blank=True)),
                ('is_background_checked', models.BooleanField(default=False)),
                ('background_check_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sugar_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together={('user', 'event')},
        ),
    ]
