# Generated by Django 5.1.7 on 2025-03-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sugar', '0001_initial'),
    ]

    operations = [
    ]
